### ISSUE TITLE
Featured Records Can Break

### ISSUE THREAD

**Issue by kalbers** [omeka/theme-freedom#3]
If three featured records are chosen to display on the homepage, but there are not three featured records, the display breaks; eg, choose Item for all three featured records and ensure there is only one featured record in the database. It will look similar to this

![image](https://github.com/omeka/theme-freedom/assets/371262/79be9225-44e3-4135-b408-a14b3fa38e72)

Notices are:
Notice
: Undefined offset: 0 in
/webdata/omeka/releases/20231130170649/themes/freedom/home/featured-records.php
on line
64

Notice
: Undefined offset: 0 in
/webdata/omeka/releases/20231130170649/themes/freedom/home/featured-records.php
on line
74

**Comment by nelsonamaya82** [comment]
Thanks @kalbers, this is fixed now in the [main](https://github.com/omeka/theme-freedom) branch and will be included in the next release.
